services:
  - type: web
    name: plateforme-citoyen1
    env: static
    buildCommand: npm install && ng build --prod
    staticPublishPath: dist/plateforme-integre
    routes:
      - type: rewrite
        source: /*
        destination: /index.html